# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design/gui_add_task_design.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogAddTask(object):
    def setupUi(self, DialogAddTask):
        DialogAddTask.setObjectName("DialogAddTask")
        DialogAddTask.resize(559, 261)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogAddTask)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(DialogAddTask)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.comboBox_type = QtWidgets.QComboBox(DialogAddTask)
        self.comboBox_type.setObjectName("comboBox_type")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_type)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_arrive = QtWidgets.QLabel(DialogAddTask)
        self.label_arrive.setEnabled(False)
        self.label_arrive.setObjectName("label_arrive")
        self.horizontalLayout_5.addWidget(self.label_arrive)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.doubleSpinBox_arrive = QtWidgets.QDoubleSpinBox(DialogAddTask)
        self.doubleSpinBox_arrive.setEnabled(False)
        self.doubleSpinBox_arrive.setDecimals(5)
        self.doubleSpinBox_arrive.setMaximum(99999.99999)
        self.doubleSpinBox_arrive.setObjectName("doubleSpinBox_arrive")
        self.horizontalLayout_5.addWidget(self.doubleSpinBox_arrive)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(DialogAddTask)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.doubleSpinBox_WCET = QtWidgets.QDoubleSpinBox(DialogAddTask)
        self.doubleSpinBox_WCET.setDecimals(5)
        self.doubleSpinBox_WCET.setMaximum(99999.99999)
        self.doubleSpinBox_WCET.setObjectName("doubleSpinBox_WCET")
        self.horizontalLayout.addWidget(self.doubleSpinBox_WCET)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_deadline = QtWidgets.QLabel(DialogAddTask)
        self.label_deadline.setObjectName("label_deadline")
        self.horizontalLayout_2.addWidget(self.label_deadline)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.doubleSpinBox_deadline = QtWidgets.QDoubleSpinBox(DialogAddTask)
        self.doubleSpinBox_deadline.setDecimals(5)
        self.doubleSpinBox_deadline.setMaximum(99999.99999)
        self.doubleSpinBox_deadline.setObjectName("doubleSpinBox_deadline")
        self.horizontalLayout_2.addWidget(self.doubleSpinBox_deadline)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_energy = QtWidgets.QLabel(DialogAddTask)
        self.label_energy.setObjectName("label_energy")
        self.horizontalLayout_3.addWidget(self.label_energy)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.doubleSpinBox_energy = QtWidgets.QDoubleSpinBox(DialogAddTask)
        self.doubleSpinBox_energy.setDecimals(5)
        self.doubleSpinBox_energy.setMaximum(99999.99999)
        self.doubleSpinBox_energy.setObjectName("doubleSpinBox_energy")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_energy)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.pushButton_add = QtWidgets.QPushButton(DialogAddTask)
        self.pushButton_add.setObjectName("pushButton_add")
        self.horizontalLayout_4.addWidget(self.pushButton_add)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.label_5.setBuddy(self.doubleSpinBox_WCET)
        self.label_arrive.setBuddy(self.doubleSpinBox_WCET)
        self.label.setBuddy(self.doubleSpinBox_WCET)
        self.label_deadline.setBuddy(self.doubleSpinBox_deadline)
        self.label_energy.setBuddy(self.doubleSpinBox_energy)

        self.retranslateUi(DialogAddTask)
        self.pushButton_add.clicked.connect(DialogAddTask.add_clicked)
        self.pushButton_add.clicked.connect(DialogAddTask.accept)
        self.comboBox_type.currentIndexChanged['QString'].connect(DialogAddTask.change_type)
        QtCore.QMetaObject.connectSlotsByName(DialogAddTask)

    def retranslateUi(self, DialogAddTask):
        _translate = QtCore.QCoreApplication.translate
        DialogAddTask.setWindowTitle(_translate("DialogAddTask", "Dialog"))
        self.label_5.setText(_translate("DialogAddTask", "Type"))
        self.comboBox_type.setItemText(0, _translate("DialogAddTask", "Periodic"))
        self.comboBox_type.setItemText(1, _translate("DialogAddTask", "Aperiodic"))
        self.label_arrive.setText(_translate("DialogAddTask", "Arrive"))
        self.label.setText(_translate("DialogAddTask", "Worst case execution time"))
        self.label_deadline.setText(_translate("DialogAddTask", "Task period, equal to deadline"))
        self.label_energy.setText(_translate("DialogAddTask", "Energy consumption"))
        self.pushButton_add.setText(_translate("DialogAddTask", "Add"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogAddTask = QtWidgets.QDialog()
    ui = Ui_DialogAddTask()
    ui.setupUi(DialogAddTask)
    DialogAddTask.show()
    sys.exit(app.exec_())

