# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design/gui_main_desing.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(657, 568)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_simulation = QtWidgets.QWidget()
        self.tab_simulation.setObjectName("tab_simulation")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_simulation)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_11 = QtWidgets.QLabel(self.tab_simulation)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_8.addWidget(self.label_11)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.pushButton_simulation_load = QtWidgets.QPushButton(self.tab_simulation)
        self.pushButton_simulation_load.setObjectName("pushButton_simulation_load")
        self.horizontalLayout_8.addWidget(self.pushButton_simulation_load)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_12 = QtWidgets.QLabel(self.tab_simulation)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_9.addWidget(self.label_12)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.checkBox_simulation_save = QtWidgets.QCheckBox(self.tab_simulation)
        self.checkBox_simulation_save.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_simulation_save.setText("")
        self.checkBox_simulation_save.setChecked(True)
        self.checkBox_simulation_save.setObjectName("checkBox_simulation_save")
        self.horizontalLayout_9.addWidget(self.checkBox_simulation_save)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.tab_simulation)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.checkBox_simulation_thermal = QtWidgets.QCheckBox(self.tab_simulation)
        self.checkBox_simulation_thermal.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_simulation_thermal.setText("")
        self.checkBox_simulation_thermal.setChecked(True)
        self.checkBox_simulation_thermal.setObjectName("checkBox_simulation_thermal")
        self.horizontalLayout_3.addWidget(self.checkBox_simulation_thermal)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.tab_simulation)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.comboBox_simulation_energy_model = QtWidgets.QComboBox(self.tab_simulation)
        self.comboBox_simulation_energy_model.setObjectName("comboBox_simulation_energy_model")
        self.horizontalLayout_4.addWidget(self.comboBox_simulation_energy_model)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.tab_simulation)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.doubleSpinBox_simulation_mesh_step = QtWidgets.QDoubleSpinBox(self.tab_simulation)
        self.doubleSpinBox_simulation_mesh_step.setObjectName("doubleSpinBox_simulation_mesh_step")
        self.horizontalLayout_5.addWidget(self.doubleSpinBox_simulation_mesh_step)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.tab_simulation)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.doubleSpinBox_simulation_accuracy = QtWidgets.QDoubleSpinBox(self.tab_simulation)
        self.doubleSpinBox_simulation_accuracy.setObjectName("doubleSpinBox_simulation_accuracy")
        self.horizontalLayout_6.addWidget(self.doubleSpinBox_simulation_accuracy)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.tabWidget.addTab(self.tab_simulation, "")
        self.tab_tasks = QtWidgets.QWidget()
        self.tab_tasks.setObjectName("tab_tasks")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_tasks)
        self.verticalLayout.setObjectName("verticalLayout")
        self.columnView_tasks_list = QtWidgets.QColumnView(self.tab_tasks)
        self.columnView_tasks_list.setObjectName("columnView_tasks_list")
        self.verticalLayout.addWidget(self.columnView_tasks_list)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.pushButton_tasks_automatic = QtWidgets.QPushButton(self.tab_tasks)
        self.pushButton_tasks_automatic.setObjectName("pushButton_tasks_automatic")
        self.horizontalLayout_2.addWidget(self.pushButton_tasks_automatic)
        self.pushButton_tasks_add = QtWidgets.QPushButton(self.tab_tasks)
        self.pushButton_tasks_add.setObjectName("pushButton_tasks_add")
        self.horizontalLayout_2.addWidget(self.pushButton_tasks_add)
        self.pushButton_tasks_delete = QtWidgets.QPushButton(self.tab_tasks)
        self.pushButton_tasks_delete.setObjectName("pushButton_tasks_delete")
        self.horizontalLayout_2.addWidget(self.pushButton_tasks_delete)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.tab_tasks, "")
        self.tab_cpu = QtWidgets.QWidget()
        self.tab_cpu.setObjectName("tab_cpu")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.tab_cpu)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_cpu)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_cpu_cores = QtWidgets.QWidget()
        self.tab_cpu_cores.setObjectName("tab_cpu_cores")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_cpu_cores)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_cpu_cores)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_cpu_cores_general = QtWidgets.QWidget()
        self.tab_cpu_cores_general.setObjectName("tab_cpu_cores_general")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.tab_cpu_cores_general)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_23 = QtWidgets.QLabel(self.tab_cpu_cores_general)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_28.addWidget(self.label_23)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem7)
        self.checkBox_cpu_cores_automatic_origins = QtWidgets.QCheckBox(self.tab_cpu_cores_general)
        self.checkBox_cpu_cores_automatic_origins.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_cpu_cores_automatic_origins.setText("")
        self.checkBox_cpu_cores_automatic_origins.setChecked(True)
        self.checkBox_cpu_cores_automatic_origins.setObjectName("checkBox_cpu_cores_automatic_origins")
        self.horizontalLayout_28.addWidget(self.checkBox_cpu_cores_automatic_origins)
        self.verticalLayout_13.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.groupBox = QtWidgets.QGroupBox(self.tab_cpu_cores_general)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.columnView__cpu_cores_avaliable_frequencies = QtWidgets.QColumnView(self.groupBox)
        self.columnView__cpu_cores_avaliable_frequencies.setObjectName("columnView__cpu_cores_avaliable_frequencies")
        self.verticalLayout_10.addWidget(self.columnView__cpu_cores_avaliable_frequencies)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem8)
        self.pushButton_cpu_cores_avaliable_frequencies_add = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_cpu_cores_avaliable_frequencies_add.setObjectName("pushButton_cpu_cores_avaliable_frequencies_add")
        self.horizontalLayout_27.addWidget(self.pushButton_cpu_cores_avaliable_frequencies_add)
        self.pushButton_cpu_cores_avaliable_frequencies_delete = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_cpu_cores_avaliable_frequencies_delete.setObjectName("pushButton_cpu_cores_avaliable_frequencies_delete")
        self.horizontalLayout_27.addWidget(self.pushButton_cpu_cores_avaliable_frequencies_delete)
        self.verticalLayout_10.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_31.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_cpu_cores_general)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.columnView_cpu_cores_selected_frequencies = QtWidgets.QColumnView(self.groupBox_2)
        self.columnView_cpu_cores_selected_frequencies.setObjectName("columnView_cpu_cores_selected_frequencies")
        self.verticalLayout_11.addWidget(self.columnView_cpu_cores_selected_frequencies)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem9)
        self.pushButton_cpu_cores_selected_frequencies_add = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_cpu_cores_selected_frequencies_add.setObjectName("pushButton_cpu_cores_selected_frequencies_add")
        self.horizontalLayout_29.addWidget(self.pushButton_cpu_cores_selected_frequencies_add)
        self.pushButton_cpu_cores_selected_frequencies_delete = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_cpu_cores_selected_frequencies_delete.setObjectName("pushButton_cpu_cores_selected_frequencies_delete")
        self.horizontalLayout_29.addWidget(self.pushButton_cpu_cores_selected_frequencies_delete)
        self.verticalLayout_11.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_31.addWidget(self.groupBox_2)
        self.verticalLayout_13.addLayout(self.horizontalLayout_31)
        self.tabWidget_3.addTab(self.tab_cpu_cores_general, "")
        self.tab_cpu_cores_physical = QtWidgets.QWidget()
        self.tab_cpu_cores_physical.setObjectName("tab_cpu_cores_physical")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_cpu_cores_physical)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.tab_cpu_cores_physical)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem10)
        self.doubleSpinBox_cpu_cores_physical_x = QtWidgets.QDoubleSpinBox(self.tab_cpu_cores_physical)
        self.doubleSpinBox_cpu_cores_physical_x.setObjectName("doubleSpinBox_cpu_cores_physical_x")
        self.horizontalLayout_10.addWidget(self.doubleSpinBox_cpu_cores_physical_x)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_9 = QtWidgets.QLabel(self.tab_cpu_cores_physical)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_11.addWidget(self.label_9)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem11)
        self.doubleSpinBox_cpu_cores_physical_y = QtWidgets.QDoubleSpinBox(self.tab_cpu_cores_physical)
        self.doubleSpinBox_cpu_cores_physical_y.setObjectName("doubleSpinBox_cpu_cores_physical_y")
        self.horizontalLayout_11.addWidget(self.doubleSpinBox_cpu_cores_physical_y)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_5 = QtWidgets.QLabel(self.tab_cpu_cores_physical)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_12.addWidget(self.label_5)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem12)
        self.doubleSpinBox_cpu_cores_physical_z = QtWidgets.QDoubleSpinBox(self.tab_cpu_cores_physical)
        self.doubleSpinBox_cpu_cores_physical_z.setObjectName("doubleSpinBox_cpu_cores_physical_z")
        self.horizontalLayout_12.addWidget(self.doubleSpinBox_cpu_cores_physical_z)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_8 = QtWidgets.QLabel(self.tab_cpu_cores_physical)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_13.addWidget(self.label_8)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem13)
        self.doubleSpinBox_cpu_cores_physical_p = QtWidgets.QDoubleSpinBox(self.tab_cpu_cores_physical)
        self.doubleSpinBox_cpu_cores_physical_p.setObjectName("doubleSpinBox_cpu_cores_physical_p")
        self.horizontalLayout_13.addWidget(self.doubleSpinBox_cpu_cores_physical_p)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_6 = QtWidgets.QLabel(self.tab_cpu_cores_physical)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_14.addWidget(self.label_6)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem14)
        self.doubleSpinBox_cpu_cores_physical_c_p = QtWidgets.QDoubleSpinBox(self.tab_cpu_cores_physical)
        self.doubleSpinBox_cpu_cores_physical_c_p.setObjectName("doubleSpinBox_cpu_cores_physical_c_p")
        self.horizontalLayout_14.addWidget(self.doubleSpinBox_cpu_cores_physical_c_p)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_7 = QtWidgets.QLabel(self.tab_cpu_cores_physical)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_15.addWidget(self.label_7)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem15)
        self.doubleSpinBox_cpu_cores_physical_k = QtWidgets.QDoubleSpinBox(self.tab_cpu_cores_physical)
        self.doubleSpinBox_cpu_cores_physical_k.setObjectName("doubleSpinBox_cpu_cores_physical_k")
        self.horizontalLayout_15.addWidget(self.doubleSpinBox_cpu_cores_physical_k)
        self.verticalLayout_5.addLayout(self.horizontalLayout_15)
        self.tabWidget_3.addTab(self.tab_cpu_cores_physical, "")
        self.tab_cpu_cores_origins = QtWidgets.QWidget()
        self.tab_cpu_cores_origins.setEnabled(False)
        self.tab_cpu_cores_origins.setObjectName("tab_cpu_cores_origins")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_cpu_cores_origins)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.columnView_cpu_cores_origins_list = QtWidgets.QColumnView(self.tab_cpu_cores_origins)
        self.columnView_cpu_cores_origins_list.setObjectName("columnView_cpu_cores_origins_list")
        self.verticalLayout_9.addWidget(self.columnView_cpu_cores_origins_list)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem16)
        self.pushButton_cpu_cores_origins_add = QtWidgets.QPushButton(self.tab_cpu_cores_origins)
        self.pushButton_cpu_cores_origins_add.setObjectName("pushButton_cpu_cores_origins_add")
        self.horizontalLayout_26.addWidget(self.pushButton_cpu_cores_origins_add)
        self.pushButton_cpu_cores_origins_delete = QtWidgets.QPushButton(self.tab_cpu_cores_origins)
        self.pushButton_cpu_cores_origins_delete.setObjectName("pushButton_cpu_cores_origins_delete")
        self.horizontalLayout_26.addWidget(self.pushButton_cpu_cores_origins_delete)
        self.verticalLayout_9.addLayout(self.horizontalLayout_26)
        self.tabWidget_3.addTab(self.tab_cpu_cores_origins, "")
        self.tab_cpu_cores_energy = QtWidgets.QWidget()
        self.tab_cpu_cores_energy.setObjectName("tab_cpu_cores_energy")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_cpu_cores_energy)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_19 = QtWidgets.QLabel(self.tab_cpu_cores_energy)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_22.addWidget(self.label_19)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem17)
        self.doubleSpinBox_cpu_cores_energy_leakage_alpha = QtWidgets.QDoubleSpinBox(self.tab_cpu_cores_energy)
        self.doubleSpinBox_cpu_cores_energy_leakage_alpha.setObjectName("doubleSpinBox_cpu_cores_energy_leakage_alpha")
        self.horizontalLayout_22.addWidget(self.doubleSpinBox_cpu_cores_energy_leakage_alpha)
        self.verticalLayout_8.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_20 = QtWidgets.QLabel(self.tab_cpu_cores_energy)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_23.addWidget(self.label_20)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem18)
        self.doubleSpinBox_cpu_cores_energy_leakage_delta = QtWidgets.QDoubleSpinBox(self.tab_cpu_cores_energy)
        self.doubleSpinBox_cpu_cores_energy_leakage_delta.setObjectName("doubleSpinBox_cpu_cores_energy_leakage_delta")
        self.horizontalLayout_23.addWidget(self.doubleSpinBox_cpu_cores_energy_leakage_delta)
        self.verticalLayout_8.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_21 = QtWidgets.QLabel(self.tab_cpu_cores_energy)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_24.addWidget(self.label_21)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem19)
        self.doubleSpinBox_cpu_cores_energy_dynamic_alpha = QtWidgets.QDoubleSpinBox(self.tab_cpu_cores_energy)
        self.doubleSpinBox_cpu_cores_energy_dynamic_alpha.setObjectName("doubleSpinBox_cpu_cores_energy_dynamic_alpha")
        self.horizontalLayout_24.addWidget(self.doubleSpinBox_cpu_cores_energy_dynamic_alpha)
        self.verticalLayout_8.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_22 = QtWidgets.QLabel(self.tab_cpu_cores_energy)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_25.addWidget(self.label_22)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem20)
        self.doubleSpinBox_cpu_cores_energy_dynamic_beta = QtWidgets.QDoubleSpinBox(self.tab_cpu_cores_energy)
        self.doubleSpinBox_cpu_cores_energy_dynamic_beta.setObjectName("doubleSpinBox_cpu_cores_energy_dynamic_beta")
        self.horizontalLayout_25.addWidget(self.doubleSpinBox_cpu_cores_energy_dynamic_beta)
        self.verticalLayout_8.addLayout(self.horizontalLayout_25)
        self.tabWidget_3.addTab(self.tab_cpu_cores_energy, "")
        self.verticalLayout_4.addWidget(self.tabWidget_3)
        self.tabWidget_2.addTab(self.tab_cpu_cores, "")
        self.tab_board = QtWidgets.QWidget()
        self.tab_board.setObjectName("tab_board")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_board)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.tab_board)
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_cpu_board_physical = QtWidgets.QWidget()
        self.tab_cpu_board_physical.setObjectName("tab_cpu_board_physical")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_cpu_board_physical)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_14 = QtWidgets.QLabel(self.tab_cpu_board_physical)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_17.addWidget(self.label_14)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem21)
        self.doubleSpinBox_cpu_board_physical_x = QtWidgets.QDoubleSpinBox(self.tab_cpu_board_physical)
        self.doubleSpinBox_cpu_board_physical_x.setObjectName("doubleSpinBox_cpu_board_physical_x")
        self.horizontalLayout_17.addWidget(self.doubleSpinBox_cpu_board_physical_x)
        self.verticalLayout_7.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_17 = QtWidgets.QLabel(self.tab_cpu_board_physical)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_20.addWidget(self.label_17)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem22)
        self.doubleSpinBox_cpu_board_physical_y = QtWidgets.QDoubleSpinBox(self.tab_cpu_board_physical)
        self.doubleSpinBox_cpu_board_physical_y.setObjectName("doubleSpinBox_cpu_board_physical_y")
        self.horizontalLayout_20.addWidget(self.doubleSpinBox_cpu_board_physical_y)
        self.verticalLayout_7.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_15 = QtWidgets.QLabel(self.tab_cpu_board_physical)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_18.addWidget(self.label_15)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem23)
        self.doubleSpinBox_cpu_board_physical_z = QtWidgets.QDoubleSpinBox(self.tab_cpu_board_physical)
        self.doubleSpinBox_cpu_board_physical_z.setObjectName("doubleSpinBox_cpu_board_physical_z")
        self.horizontalLayout_18.addWidget(self.doubleSpinBox_cpu_board_physical_z)
        self.verticalLayout_7.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_18 = QtWidgets.QLabel(self.tab_cpu_board_physical)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_21.addWidget(self.label_18)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem24)
        self.doubleSpinBox_cpu_board_physical_p = QtWidgets.QDoubleSpinBox(self.tab_cpu_board_physical)
        self.doubleSpinBox_cpu_board_physical_p.setObjectName("doubleSpinBox_cpu_board_physical_p")
        self.horizontalLayout_21.addWidget(self.doubleSpinBox_cpu_board_physical_p)
        self.verticalLayout_7.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_16 = QtWidgets.QLabel(self.tab_cpu_board_physical)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_19.addWidget(self.label_16)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem25)
        self.doubleSpinBox_cpu_board_physical_c_p = QtWidgets.QDoubleSpinBox(self.tab_cpu_board_physical)
        self.doubleSpinBox_cpu_board_physical_c_p.setObjectName("doubleSpinBox_cpu_board_physical_c_p")
        self.horizontalLayout_19.addWidget(self.doubleSpinBox_cpu_board_physical_c_p)
        self.verticalLayout_7.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_13 = QtWidgets.QLabel(self.tab_cpu_board_physical)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_16.addWidget(self.label_13)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem26)
        self.doubleSpinBox_cpu_board_physical_k = QtWidgets.QDoubleSpinBox(self.tab_cpu_board_physical)
        self.doubleSpinBox_cpu_board_physical_k.setObjectName("doubleSpinBox_cpu_board_physical_k")
        self.horizontalLayout_16.addWidget(self.doubleSpinBox_cpu_board_physical_k)
        self.verticalLayout_7.addLayout(self.horizontalLayout_16)
        self.tabWidget_4.addTab(self.tab_cpu_board_physical, "")
        self.verticalLayout_6.addWidget(self.tabWidget_4)
        self.tabWidget_2.addTab(self.tab_board, "")
        self.horizontalLayout_7.addWidget(self.tabWidget_2)
        self.tabWidget.addTab(self.tab_cpu, "")
        self.tab_environment = QtWidgets.QWidget()
        self.tab_environment.setObjectName("tab_environment")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.tab_environment)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_24 = QtWidgets.QLabel(self.tab_environment)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_32.addWidget(self.label_24)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem27)
        self.doubleSpinBox_environment_env_temperature = QtWidgets.QDoubleSpinBox(self.tab_environment)
        self.doubleSpinBox_environment_env_temperature.setObjectName("doubleSpinBox_environment_env_temperature")
        self.horizontalLayout_32.addWidget(self.doubleSpinBox_environment_env_temperature)
        self.verticalLayout_14.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_25 = QtWidgets.QLabel(self.tab_environment)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_33.addWidget(self.label_25)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem28)
        self.doubleSpinBox_environment_max_temperature = QtWidgets.QDoubleSpinBox(self.tab_environment)
        self.doubleSpinBox_environment_max_temperature.setObjectName("doubleSpinBox_environment_max_temperature")
        self.horizontalLayout_33.addWidget(self.doubleSpinBox_environment_max_temperature)
        self.verticalLayout_14.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_26 = QtWidgets.QLabel(self.tab_environment)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_34.addWidget(self.label_26)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem29)
        self.doubleSpinBox_environment_convection_factor = QtWidgets.QDoubleSpinBox(self.tab_environment)
        self.doubleSpinBox_environment_convection_factor.setObjectName("doubleSpinBox_environment_convection_factor")
        self.horizontalLayout_34.addWidget(self.doubleSpinBox_environment_convection_factor)
        self.verticalLayout_14.addLayout(self.horizontalLayout_34)
        self.tabWidget.addTab(self.tab_environment, "")
        self.tab_scheduler = QtWidgets.QWidget()
        self.tab_scheduler.setObjectName("tab_scheduler")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.tab_scheduler)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_27 = QtWidgets.QLabel(self.tab_scheduler)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_35.addWidget(self.label_27)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem30)
        self.comboBox_scheduler_select = QtWidgets.QComboBox(self.tab_scheduler)
        self.comboBox_scheduler_select.setObjectName("comboBox_scheduler_select")
        self.horizontalLayout_35.addWidget(self.comboBox_scheduler_select)
        self.verticalLayout_15.addLayout(self.horizontalLayout_35)
        self.tabWidget.addTab(self.tab_scheduler, "")
        self.tab_output = QtWidgets.QWidget()
        self.tab_output.setObjectName("tab_output")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.tab_output)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.tabWidget_5 = QtWidgets.QTabWidget(self.tab_output)
        self.tabWidget_5.setObjectName("tabWidget_5")
        self.tab_output_general = QtWidgets.QWidget()
        self.tab_output_general.setObjectName("tab_output_general")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.tab_output_general)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.label_29 = QtWidgets.QLabel(self.tab_output_general)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_37.addWidget(self.label_29)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_37.addItem(spacerItem31)
        self.label_output_path = QtWidgets.QLabel(self.tab_output_general)
        self.label_output_path.setObjectName("label_output_path")
        self.horizontalLayout_37.addWidget(self.label_output_path)
        self.pushButton_output_change_path = QtWidgets.QPushButton(self.tab_output_general)
        self.pushButton_output_change_path.setObjectName("pushButton_output_change_path")
        self.horizontalLayout_37.addWidget(self.pushButton_output_change_path)
        self.verticalLayout_16.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.label_31 = QtWidgets.QLabel(self.tab_output_general)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_38.addWidget(self.label_31)
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_38.addItem(spacerItem32)
        self.lineEdit_output_base_naming = QtWidgets.QLineEdit(self.tab_output_general)
        self.lineEdit_output_base_naming.setObjectName("lineEdit_output_base_naming")
        self.horizontalLayout_38.addWidget(self.lineEdit_output_base_naming)
        self.verticalLayout_16.addLayout(self.horizontalLayout_38)
        self.tabWidget_5.addTab(self.tab_output_general, "")
        self.tab_output_selected = QtWidgets.QWidget()
        self.tab_output_selected.setObjectName("tab_output_selected")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.tab_output_selected)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.columnView_output_selected_drawers = QtWidgets.QColumnView(self.tab_output_selected)
        self.columnView_output_selected_drawers.setObjectName("columnView_output_selected_drawers")
        self.verticalLayout_18.addWidget(self.columnView_output_selected_drawers)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_36.addItem(spacerItem33)
        self.pushButton_output_selected_add = QtWidgets.QPushButton(self.tab_output_selected)
        self.pushButton_output_selected_add.setObjectName("pushButton_output_selected_add")
        self.horizontalLayout_36.addWidget(self.pushButton_output_selected_add)
        self.pushButton_output_selected_delete = QtWidgets.QPushButton(self.tab_output_selected)
        self.pushButton_output_selected_delete.setObjectName("pushButton_output_selected_delete")
        self.horizontalLayout_36.addWidget(self.pushButton_output_selected_delete)
        self.verticalLayout_18.addLayout(self.horizontalLayout_36)
        self.tabWidget_5.addTab(self.tab_output_selected, "")
        self.verticalLayout_17.addWidget(self.tabWidget_5)
        self.tabWidget.addTab(self.tab_output, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        self.label_status.setObjectName("label_status")
        self.horizontalLayout.addWidget(self.label_status)
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem34)
        self.pushButton_start_simualtion = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start_simualtion.setObjectName("pushButton_start_simualtion")
        self.horizontalLayout.addWidget(self.pushButton_start_simualtion)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.label_11.setBuddy(self.pushButton_simulation_load)
        self.label_12.setBuddy(self.checkBox_simulation_save)
        self.label_2.setBuddy(self.checkBox_simulation_thermal)
        self.label.setBuddy(self.comboBox_simulation_energy_model)
        self.label_4.setBuddy(self.doubleSpinBox_simulation_mesh_step)
        self.label_3.setBuddy(self.doubleSpinBox_simulation_accuracy)
        self.label_23.setBuddy(self.checkBox_cpu_cores_automatic_origins)
        self.label_10.setBuddy(self.doubleSpinBox_cpu_cores_physical_x)
        self.label_9.setBuddy(self.doubleSpinBox_cpu_cores_physical_y)
        self.label_5.setBuddy(self.doubleSpinBox_cpu_cores_physical_z)
        self.label_8.setBuddy(self.doubleSpinBox_cpu_cores_physical_p)
        self.label_6.setBuddy(self.doubleSpinBox_cpu_cores_physical_c_p)
        self.label_7.setBuddy(self.doubleSpinBox_cpu_cores_physical_k)
        self.label_19.setBuddy(self.doubleSpinBox_cpu_cores_energy_leakage_alpha)
        self.label_20.setBuddy(self.doubleSpinBox_cpu_cores_energy_leakage_delta)
        self.label_21.setBuddy(self.doubleSpinBox_cpu_cores_energy_dynamic_alpha)
        self.label_22.setBuddy(self.doubleSpinBox_cpu_cores_energy_dynamic_beta)
        self.label_14.setBuddy(self.doubleSpinBox_cpu_board_physical_x)
        self.label_17.setBuddy(self.doubleSpinBox_cpu_board_physical_y)
        self.label_15.setBuddy(self.doubleSpinBox_cpu_board_physical_z)
        self.label_18.setBuddy(self.doubleSpinBox_cpu_board_physical_p)
        self.label_16.setBuddy(self.doubleSpinBox_cpu_board_physical_c_p)
        self.label_13.setBuddy(self.doubleSpinBox_cpu_board_physical_k)
        self.label_24.setBuddy(self.doubleSpinBox_environment_env_temperature)
        self.label_25.setBuddy(self.doubleSpinBox_environment_max_temperature)
        self.label_26.setBuddy(self.doubleSpinBox_environment_convection_factor)
        self.label_27.setBuddy(self.comboBox_simulation_energy_model)
        self.label_29.setBuddy(self.pushButton_output_change_path)
        self.label_31.setBuddy(self.lineEdit_output_base_naming)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_5.setCurrentIndex(0)
        self.checkBox_simulation_save.toggled['bool'].connect(MainWindow.simulate_thermal_state_changed)
        self.pushButton_simulation_load.clicked.connect(MainWindow.load_json)
        self.pushButton_start_simualtion.clicked.connect(MainWindow.start_simulation)
        self.pushButton_tasks_add.clicked.connect(MainWindow.add_task)
        self.pushButton_tasks_automatic.clicked.connect(MainWindow.generate_automatic_tasks)
        self.pushButton_tasks_delete.clicked.connect(self.columnView_tasks_list.clearSelection)
        self.pushButton_cpu_cores_origins_add.clicked.connect(MainWindow.add_origin)
        self.pushButton_cpu_cores_origins_delete.clicked.connect(self.columnView_cpu_cores_origins_list.clearSelection)
        self.pushButton_cpu_cores_avaliable_frequencies_delete.clicked.connect(self.columnView__cpu_cores_avaliable_frequencies.clearSelection)
        self.pushButton_cpu_cores_selected_frequencies_delete.clicked.connect(self.columnView_cpu_cores_selected_frequencies.clearSelection)
        self.pushButton_cpu_cores_avaliable_frequencies_add.clicked.connect(MainWindow.add_available_frequency)
        self.pushButton_cpu_cores_selected_frequencies_add.clicked.connect(MainWindow.add_selected_frequency)
        self.checkBox_cpu_cores_automatic_origins.toggled['bool'].connect(MainWindow.generate_automatic_origins_changed)
        self.pushButton_output_change_path.clicked.connect(MainWindow.change_output_path)
        self.pushButton_output_selected_delete.clicked.connect(self.columnView_output_selected_drawers.clearSelection)
        self.pushButton_output_selected_add.toggled['bool'].connect(MainWindow.add_output)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_11.setText(_translate("MainWindow", "Load JSON specification"))
        self.pushButton_simulation_load.setText(_translate("MainWindow", "Load"))
        self.label_12.setText(_translate("MainWindow", "Save as specification as JSON"))
        self.label_2.setText(_translate("MainWindow", "Simulate thermal"))
        self.label.setText(_translate("MainWindow", "Energy generation model"))
        self.label_4.setText(_translate("MainWindow", "Mesh step size (mm)"))
        self.label_3.setText(_translate("MainWindow", "Accuracy (s)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_simulation), _translate("MainWindow", "Simulation"))
        self.pushButton_tasks_automatic.setText(_translate("MainWindow", "Automatic generation"))
        self.pushButton_tasks_add.setText(_translate("MainWindow", "Add"))
        self.pushButton_tasks_delete.setText(_translate("MainWindow", "Delete"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_tasks), _translate("MainWindow", "Tasks"))
        self.label_23.setText(_translate("MainWindow", "Generate automatic origins"))
        self.groupBox.setTitle(_translate("MainWindow", "Avaliable frequencies"))
        self.pushButton_cpu_cores_avaliable_frequencies_add.setText(_translate("MainWindow", "Add"))
        self.pushButton_cpu_cores_avaliable_frequencies_delete.setText(_translate("MainWindow", "Delete"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Selected frequencies"))
        self.pushButton_cpu_cores_selected_frequencies_add.setText(_translate("MainWindow", "Add"))
        self.pushButton_cpu_cores_selected_frequencies_delete.setText(_translate("MainWindow", "Delete"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_cpu_cores_general), _translate("MainWindow", "General"))
        self.label_10.setText(_translate("MainWindow", "x ( mm )"))
        self.label_9.setText(_translate("MainWindow", "y ( mm )"))
        self.label_5.setText(_translate("MainWindow", "z ( mm )"))
        self.label_8.setText(_translate("MainWindow", "Density ( Kg / cm^3 )"))
        self.label_6.setText(_translate("MainWindow", "Specific heat capacities ( J /Kg K )"))
        self.label_7.setText(_translate("MainWindow", "Thermal conductivity ( W / m ºC )"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_cpu_cores_physical), _translate("MainWindow", "Physical"))
        self.pushButton_cpu_cores_origins_add.setText(_translate("MainWindow", "Add"))
        self.pushButton_cpu_cores_origins_delete.setText(_translate("MainWindow", "Delete"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_cpu_cores_origins), _translate("MainWindow", "Origins"))
        self.label_19.setText(_translate("MainWindow", "Leakage alpha"))
        self.label_20.setText(_translate("MainWindow", "Leakage delta"))
        self.label_21.setText(_translate("MainWindow", "Dynamic alpha"))
        self.label_22.setText(_translate("MainWindow", "Dynamic beta"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_cpu_cores_energy), _translate("MainWindow", "Energy consumption"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_cpu_cores), _translate("MainWindow", "Cores"))
        self.label_14.setText(_translate("MainWindow", "x ( mm )"))
        self.label_17.setText(_translate("MainWindow", "y ( mm )"))
        self.label_15.setText(_translate("MainWindow", "z ( mm )"))
        self.label_18.setText(_translate("MainWindow", "Density ( Kg / cm^3 )"))
        self.label_16.setText(_translate("MainWindow", "Specific heat capacities ( J / Kg K )"))
        self.label_13.setText(_translate("MainWindow", "Thermal conductivity ( W / m ºC )"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_cpu_board_physical), _translate("MainWindow", "Physical"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_board), _translate("MainWindow", "Board"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_cpu), _translate("MainWindow", "CPU"))
        self.label_24.setText(_translate("MainWindow", "Environment temperature ( º C )"))
        self.label_25.setText(_translate("MainWindow", "Maximum temperature ( º C )"))
        self.label_26.setText(_translate("MainWindow", "Convection factor ( W / mm^2 º C )"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_environment), _translate("MainWindow", "Environment"))
        self.label_27.setText(_translate("MainWindow", "Scheduler"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_scheduler), _translate("MainWindow", "Scheduler"))
        self.label_29.setText(_translate("MainWindow", "Output path"))
        self.label_output_path.setText(_translate("MainWindow", "./out/"))
        self.pushButton_output_change_path.setText(_translate("MainWindow", "Change"))
        self.label_31.setText(_translate("MainWindow", "Base naming"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_output_general), _translate("MainWindow", "General"))
        self.pushButton_output_selected_add.setText(_translate("MainWindow", "Add"))
        self.pushButton_output_selected_delete.setText(_translate("MainWindow", "Delete"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_output_selected), _translate("MainWindow", "Selected"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_output), _translate("MainWindow", "Output"))
        self.label_status.setText(_translate("MainWindow", "Status"))
        self.pushButton_start_simualtion.setText(_translate("MainWindow", "Start Simulation"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

